steps:
  # Build the multi-stage Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mthds-repo/mthds-app:$COMMIT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mthds-repo/mthds-app:latest'
      - '.'

  # Push the generated image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mthds-repo/mthds-app'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mthds-repo/mthds-app:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mthds-repo/mthds-app:latest'
