# Generated by Django 6.0.3 on 2026-03-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_board_is_archived_list_is_archived_taskcard_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
