# Generated by Django 6.0.3 on 2026-03-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_taskcard_assignees_activitylog_boardlabel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardlabel',
            unique_together=set(),
        ),
    ]
