# Generated by Django 6.0.3 on 2026-03-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_boardlabel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='color_boost',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
