# Generated by Django 6.0.3 on 2026-03-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_alter_list_color_alter_taskcard_color_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
