# Generated by Django 6.0.3 on 2026-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='agent_state_mapping',
            field=models.CharField(blank=True, choices=[('backlog', 'Backlog'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], help_text='Standardized mapping for the CLI/Agent', max_length=20, null=True),
        ),
    ]
